// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Actions: typeof import('./components/Header/Actions.vue')['default']
    Breadcrumbs: typeof import('./components/Breadcrumbs/Breadcrumbs.vue')['default']
    BreadcrumbsItem: typeof import('./components/Breadcrumbs/BreadcrumbsItem.vue')['default']
    CookieNotification: typeof import('./components/CookieNotification/CookieNotification.vue')['default']
    Define: typeof import('./components/Dynamic/Define.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Logger: typeof import('./components/Logger/Logger.vue')['default']
    MobileMenu: typeof import('./components/Header/MobileMenu.vue')['default']
    Navigation: typeof import('./components/Header/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wysiwyg: typeof import('./components/Dynamic/Wysiwyg/Wysiwyg.vue')['default']
    Youtube: typeof import('./components/Youtube/Youtube.vue')['default']
  }
}
